### ISSUE TITLE
Small Feature Suggestion

### ISSUE THREAD

**Issue by ashaikh** [tigros/livewriter#1]
I was playing around with this today and if you can add an option to suppress messages such as "[ Silence ]" or [Blank Audio] etc. As a user is going through the dictation sometimes you want to pause or look something up and this inserts a lot of cleanup work at the end for the user to do.

Ideally it would identify the different voices speaking and indicate that somehow "Person 1:" as an option.

**Comment by tigros** [comment]
where do i get a list of possibilities?

So far I've got [Silence] and [Music], you say [Blank Audio] don't think i've seen that one.  Any others?

I'll get started on those, it will be easy to add more later.

No, can't differentiate people, not me anyway. Maybe someone will do that one day.

**Comment by tigros** [comment]
never mind, i did a search of the 26k srt's i've got for [ i can check for [ ] that have 1 or 2 words inside that should do it.

**Comment by tigros** [comment]
that should do it v1.1
