### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by nandxorandor** [tigros/livewriter#2]
Hi,
I tried to run the main.exe but nothing happened! 
I do have whisper and whisperer apps and they run nicely, but this one didn't.
How does this work? I am pretty sure I missed something here!
tx,
A.K.

**Comment by tigros** [comment]
run livewriter.exe not main.exe

**Comment by nandxorandor** [comment]
There is no livewriter.exe file! I will try to re-download the repo and see. Thanks for the response.

**Comment by tigros** [comment]
ah ok that's an antivirus problem, ur not the first.

**Comment by nandxorandor** [comment]
Thank you again!
