### ISSUE TITLE
Where is the output of this program?

### ISSUE THREAD

**Issue by Chenm4** [tigros/livewriter#3]
![image](https://github.com/tigros/livewriter/assets/98648589/add0f9b7-d7f7-467c-ab19-6de0db4999dd)
Where does this program output the contents of the const-me whisper?
The function I want is to turn the translated content generated by Whisper into real-time subtitles, similar to YouTube subtitles. The current result of my translation is as follows
![image](https://github.com/tigros/livewriter/assets/98648589/1affeece-bf10-46b3-b320-07536a2f6d6f)
I want each of their sentences to be turned into subtitles and displayed on the screen in real time. I would like to ask if your program can achieve this function.
Thank you very much for this program, whether it is useful to me or not

**Comment by tigros** [comment]
you just have to place the cursor on something that accepts input, like notepad.

the files are temporarily stored in the %TEMP% folder.
